version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  is-it-down:
    lang: python3-flask
    handler: ./is-it-down
    image: ghcr.io/lucasroesler/is-it-down:latest
    environment:
      TRACING: "true"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo.default.svc.cluster.local:4317
      OTEL_PROPAGATORS: tracecontext,baggage,jaeger
      LOG_LEVEL: "INFO"
